FUTURES_SYMBOLS = [
    'BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','AVAXUSDT','LINKUSDT','TRXUSDT','DOTUSDT','LTCUSDT','BCHUSDT','SUIUSDT','APTUSDT','ARBUSDT','OPUSDT','NEARUSDT','FILUSDT','ATOMUSDT','INJUSDT','AAVEUSDT','UNIUSDT','ETCUSDT','TONUSDT','SHIBUSDT','WIFUSDT','BONKUSDT','FLOKIUSDT','PEPEUSDT'
]
FOREX_SYMBOLS = ['XAUUSD','BTCUSD']

class MarketDataService:
    def symbols(self, market: str) -> list[str]:
        return FOREX_SYMBOLS if market.upper() == 'FOREX' else FUTURES_SYMBOLS

market_data = MarketDataService()
